import React from "react";
import styles from './bubbleBackground.module.css'

const BubbleBackground = () => {
  return (
    <div style={{zIndex: 0}} >
      <svg version="1.1" xmlns="http://www.w3.org/2000/svg">
        <defs>
          <filter id="goo">
            <fegaussianblur
              in="SourceGraphic"
              result="blur"
              stdDeviation="10"
            ></fegaussianblur>
            <fecolormatrix
              in="blur"
              mode="matrix"
              result="goo"
              values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 18 -7"
            ></fecolormatrix>
            <feblend in2="goo" in="SourceGraphic"></feblend>
          </filter>
        </defs>
      </svg>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
      <span className={styles.particle}></span>
    </div>
  );
};

export default BubbleBackground;
